language: node_js

matrix:
  include:
    - os: linux
      node_js: '8'
      sudo: required
      env: DISPLAY=':99.0'
      dist: trusty
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
    - os: osx
      node_js: '8'
      sudo: required
      env: XQUARTZ_VERSION=2.7.7
before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update > /dev/null
      brew cask install google-chrome
      curl -L -O http://xquartz.macosforge.org/downloads/SL/XQuartz-${XQUARTZ_VERSION}.dmg
      hdiutil mount XQuartz-${XQUARTZ_VERSION}.dmg
      sudo installer -store -pkg /Volumes/XQuartz-${XQUARTZ_VERSION}/XQuartz.pkg -target /
      hdiutil unmount /Volumes/XQuartz-${XQUARTZ_VERSION}
    fi
install:
  - npm install
  - npm run build
before_script:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sh -e /etc/init.d/xvfb start
    fi
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      /opt/X11/bin/xterm&
    fi
    
script:
  - npm test
